<center><img src="https://i.pinimg.com/webp/1200x/47/6f/07/476f07bee96bdbc9b0c97acbc01175d3.webp" width="1200" height="300"></center>

## <b>1 <span style='color:#F1A424'>|</span>Text to Vector _ (count base)</b> 

<div style="color:white;display:fill;border-radius:8px;font-size:100%; letter-spacing:1.0px;"><p style="padding: 5px;color:white;text-align:left;"><b><span style='color:#F1A424'>WHAT WE WILL DO IN THIS SECTION</span></b></p></div>

- 날짜 : 2026-06-09(화요일), 오후 수업
- 핵심 내용 : 텍스트를 벡터화
- feqture 추출 : 자연어 텍스트에서 중요한 특징 ➔ 의미적, 문법적 특성을 수치화 <br> 텍스트 데이터의 가장 필수적인 전처리 과정 
- 개념 : Feature 추출 **<mark style="background-color:#fffbc9;color:black;border-
radius:5px;opacity:1.0"> Subword 방식의 tokenizers  library</mark>**
- 주요 방법론
    1. Count-Based Word representation : 단어가 나오는 빈도수 기반 표현방식 
        - bag of word, TF-IDF(+확률)
    2. Word Embedding : 단어를 고정된 Vector로 표현. ➔고정 : 문맥에 상관없이 같은 단어는 같은 값으로 표현
        - word2vec, fastext, glove
    3. contextualized word embedding
        - 문맥을 고려한 Word embedding 방식 ➔ 동적 vector 표현 방식 
    4. 

<br>

<div style="color:white;display:fill;border-radius:8px;background-color:#323232;font-size:150%; letter-spacing:1.0px"><p style="padding: 12px;color:white;"><b><b><span style='color:white'><span style='color:#F1A424'>1.1 | </span></span></b>Count Based Word Representation | DTM  </b></p></div>

- 문서를 구성하는 단어들이 몇 번 나왔는지를 표현하는 행렬(matrix)로 벡터화 ( 테이블 형태)
- DTM / TDM (행과 열에 무엇을 두는가의 차이)
    - 행 : 문서 번호(Doc)
    - 열 : 모든 문서에서 나온 단어(Term)
    - 값 : 출연 빈도 수  
- 동일한 정보를 담고 있으며 두 행렬에 담긴 값만 서로 바뀐 형태임.
- 단점 :
    - 100개 문서의 모든 단어들이 다 들어감 ➔ 0이 너무 많은 희소행렬이됨.
    - 딥러닝보다는 머신러닝에서 주로 사용됨 
- 구현방법:
    1. 어휘사전(vocab) 생성 : 전체 문서에 나온 단어 수집하고 단어마다 고유 index 부여
    2. 문장과 단어간의 dtm 만들기
- 사이킷런 활용 : `Scikit-learn CountVectorizer`
- 파라미터 :
    - `stop_word`
    - `max_df` : int(횟수), float(비율) ➔ 특정 횟수 이상 나오는 것은 무시하도록 설정
    - `min_df`: 최소한 이정도는 나와야한다. (무시할 횟수/ 무시할 비율)
    - max_features: 최대 token수 : 빈도수가 높은 순서대로 정렬 ➔ 지정한 max_features 개수만큼 사용

In [1]:
!uv pip install scikit-learn

Checked 1 package in 523ms

In [6]:
# 문서리스트
## 리스트의 각 원소들이 각 문서(doc)에 해당함. ➔ 기사 1개, 논문 1개 등.

text = ["나는 야구를 좋아합니다. 나는 축구를 좋아하지 않습니다.", # - doc1
        "친구는 야구와 축구를 좋아합니다. 야구보다 축구를 더 좋아합니다.", #-doc2
        "나는 축구를 더 좋아합니다. 영국 축구 리그보다 이탈리아 축구 리그를 더 좋아합니다.", #- doc3
        "나는 농구를 좋아하지 않습니다. 배구도 좋아하지 않습니다.", #- doc4
        "나는 액션영화를 좋아합니다.", #- doc5
        "어제 비빕밥을 먹었습니다."]#- doc6

stop_words = list('은는이가을를도.,') # 대표적인 조사들과 마침표를 리스트로 부여

print("문서개수: ", len(text))
print(stop_words)

문서개수:  6
['은', '는', '이', '가', '을', '를', '도', '.', ',']

In [11]:
from kiwipiepy import Kiwi

a =  Kiwi()

a.tokenize(text[0]) # 토큰별로 잘라서 token 객체에 담아서 제공 
# 토큰의 원형값을 뽑아주는 것 : lemma
[token.lemma for token in a.tokenize(text[0])] # 이렇게 모인 값들 중에 stopwords 에 존재하는 경우 빼자 
[token.lemma for token in a.tokenize(text[0]) if token.form not in stop_words]

['나', '야구', '좋아하다', 'ᆸ니다', '나', '축구', '좋아하다', '지', '않다', '습니다']

In [12]:
# 전처리 및 토큰화 ➔ 형태소 기반 토큰화 진행
from kiwipiepy import Kiwi

kiwi =  Kiwi()

def tokenizer(doc:str) -> list:
    '''문서를 받아서 형태소 기반으로 토큰화해서 토큰 목록을 리스트로 반환'''
    tokens = kiwi.tokenize(doc) # 토큰리스트를 제공 : list[token]
    
    # 불용어 제외 & token 객체에서 원형값(lemma)만 추출해서 리스트로 저장
    tokens = [token.lemma for token in tokens if token.form not in stop_words]
    return tokens

tokenizer(text[0])

['나', '야구', '좋아하다', 'ᆸ니다', '나', '축구', '좋아하다', '지', '않다', '습니다']

In [17]:
# 사이킷런의 CountVectorizer를 활용해서 text to vector 작업 실행
## 문서의 의미를 표현하는 숫자 벡터로 변환
import sklearn

# 모델 출력 방식을 'text'로 변경 (기본값은 'diagram')
sklearn.set_config(display="text")

from sklearn.feature_extraction.text import CountVectorizer #사이킷런은 크게 변환기(전처리용 거의 다른 값으로 바꿔주는 애들_)와 추론기 : 모델 클래스들  그 중에서 countvectorizer 는 변환기

cv = CountVectorizer(
    #문서(str)을 받아서 토큰화하는 함수(callerable 설정) 생략하게 될 경우 token pattertn의 파라미터 설정을 따르게 됨. (기본 공백 / 구두점)
    token_pattern=None,
    tokenizer=tokenizer 
)

# 학습(fit)
cv.fit(text) # 입력: list[str-문서] ➔ fit(); 단어(토큰)들 추출

CountVectorizer(token_pattern=None,
                tokenizer=<function tokenizer at 0x0000020AE9C90EA0>)

In [19]:
dtm = cv.transform(text)
dtm

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 44 stored elements and shape (6, 25)>

In [22]:
arr = dtm.toarray()
print(arr.shape)
arr

(6, 25)

array([[1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 2,
        1, 1, 0],
       [2, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 2,
        0, 2, 1],
       [2, 1, 0, 2, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 2,
        0, 3, 0],
       [0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2,
        2, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
        0, 0, 0],
       [0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
        0, 0, 0]])

**<mark style="background-color: #ffdf3d;color:black;border-radius:5px;opacity:1.0">🤔나름대로 해석하기 </mark>** 
1. 문장에 비해서 단어가 너무 많아서 거의 다 0 ➔ sparse 
2. (6,25) ➔ 문서 : 6, 단어 : 25
3. 실제 논문을 1000-2000개 돌린다면 단어 수가 엄청 많아짐 전체적으로는 0이 많지만 빈도가 높은 애들은 count가 크게 찍힘
4. 개별 문서 하나하나가 데이터의 행이되고, 피쳐가 의미하는 게 **단어** 값이 단어의 빈도수

In [25]:
# 데이터프레임으로 확인 ➔ 모델링에는 ARR 그대로 들어가면 됨 JUST 가독성을 위해
import pandas as pd
import numpy as np

dtm_df = pd.DataFrame(
    arr,
    columns = cv.get_feature_names_out(),
    index = [f"{i+1}번 문서" for i in range(arr.shape[0])] # shape의 0번 ➔ 데이터 개수
)

pd.options.display.max_columns = None

dtm_df.head()

,ᆸ니다,나,농구,더,리그,먹다,밥,배구,보다,비,빕,습니다,않다,액션,야구,어제,었,영국,영화,와,이탈리아,좋아하다,지,축구,친구
1번 문서,1,2,0,0,0,0,0,0,0,0,0,1,1,0,1,0,0,0,0,0,0,2,1,1,0
2번 문서,2,0,0,1,0,0,0,0,1,0,0,0,0,0,2,0,0,0,0,1,0,2,0,2,1
3번 문서,2,1,0,2,2,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,2,0,3,0
4번 문서,0,1,1,0,0,0,0,1,0,0,0,2,2,0,0,0,0,0,0,0,0,2,2,0,0
5번 문서,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0

In [27]:
tdm_df = dtm_df.T
tdm_df

      1번 문서  2번 문서  3번 문서  4번 문서  5번 문서  6번 문서
ᆸ니다       1      2      2      0      1      0
나         2      0      1      1      1      0
농구        0      0      0      1      0      0
더         0      1      2      0      0      0
리그        0      0      2      0      0      0
먹다        0      0      0      0      0      1
밥         0      0      0      0      0      1
배구        0      0      0      1      0      0
보다        0      1      1      0      0      0
비         0      0      0      0      0      1
빕         0      0      0      0      0      1
습니다       1      0      0      2      0      1
않다        1      0      0      2      0      0
액션        0      0      0      0      1      0
야구        1      2      0      0      0      0
어제        0      0      0      0      0      1
었         0      0      0      0      0      1
영국        0      0      1      0      0      0
영화        0      0      0      0      1      0
와         0      1      0      0      0      0
이탈리아      0      0      1      0      0      0
좋아하다      2      2      2      2      1      0
지         1      0      0      2      0      0
축구        1      2      3      0      0      0
친구        0      1      0      0      0      0

**<mark style="background-color: #ffdf3d;color:black;border-radius:6px;opacity:1.0;padding: 6px;letter-spacing:0.5px;">N-Gram </mark>** 
1. 옆에 있는 애들이랑 묶어서 단어로 취급
2. bow 와 다른점 : bag은 순서를 아예 취급 안 함 ➔ 하지만 cv의 경우 고려
3. n을 너무 크게 잡으면 희소성의 문제 발생
4. n이 너무 작으면 단어간의 관계성이 표현x
5. 적당한 n을 찾는 게 중요하다 (보통은 3-5그램 사용)

In [29]:
# N-Gram 
cv2 = CountVectorizer(
    tokenizer=tokenizer,
    token_pattern=None,
    ngram_range=(1,3)
)

<div style="color:white;display:fill;border-radius:8px;background-color:#323232;font-size:150%; letter-spacing:1.0px"><p style="padding: 12px;color:white;"><b><b><span style='color:white'><span style='color:#F1A424'>1.2 | 
</span></span></b>TF-IDF(Term Frequency|inverse document frequency)</b></p></div>

- 개별 문서에 많이 나오는 단어가 높은 값을 가지도록 함. 동시에 여러 문서에서 자주 나오는 단어에는 페널티 
- 모든 문서에서 단어가 많이 등장('을','를',' 야구') <br> 하는 경우 언어 특성. 주제상 많이 등장하는 단어임.
- 구현방법:
    - TF(Term Frequency) : 해당 단어가 해당 문서에서 몇번 나오는지
    - DF(Documnet Frequency) : 해당 단어가 몇개의 문서에서 나오는지
    - IDF : DF의 역수 (전체문서수 / 해당 단어가 나오는 문서수)
    - TF IDF의 정의 : TF*log idf
- 사이킷런의 `TfidfVectorizer`

In [40]:
from sklearn import set_config
set_config(display='text')

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    tokenizer= tokenizer   
)

tfidf.fit(text)

d:\nlp_study_log\Nlp_study\.venv\Lib\site-packages\sklearn\feature_extraction\text.py:527: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

TfidfVectorizer(tokenizer=<function tokenizer at 0x0000020AE9C90EA0>)

In [42]:
# 변환하기
f_vector = tfidf.transform(text)
f_vector.toarray()

array([[0.24664467, 0.49328934, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.2878256 , 0.34091705, 0.        , 0.34091705,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.4259948 , 0.34091705, 0.2878256 , 0.        ],
       [0.36775636, 0.        , 0.        , 0.25415999, 0.        ,
        0.        , 0.        , 0.        , 0.25415999, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.50831998,
        0.        , 0.        , 0.        , 0.        , 0.3099458 ,
        0.        , 0.31758703, 0.        , 0.42915865, 0.3099458 ],
       [0.2922292 , 0.1461146 , 0.        , 0.40392487, 0.49258271,
        0.        , 0.        , 0.        , 0.20196243, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.24629136, 0.        , 0.        ,
        0.24629136, 0.25236329, 0.        , 0.51153169, 0.        ],
       [0.        , 0.1813778 , 0.30573114, 0.        , 0.        ,
        0.        , 0.        , 0.30573114, 0.        , 0.        ,
        0.        , 0.42332293, 0.50140782, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.31326847, 0.50140782, 0.        , 0.        ],
       [0.34445319, 0.34445319, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.58061168, 0.        ,
        0.        , 0.        , 0.        , 0.58061168, 0.        ,
        0.        , 0.29746288, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.39285843, 0.39285843, 0.        , 0.        , 0.39285843,
        0.39285843, 0.27198077, 0.        , 0.        , 0.        ,
        0.39285843, 0.39285843, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ]])

In [43]:
tf_idf = pd.DataFrame(
    f_vector.toarray(),
    columns=tfidf.get_feature_names_out(),
    index = [f"{i+1}번 문서" for i in range(arr.shape[0])], # shape의 0번 ➔ 데이터 개수
)

In [44]:
tf_idf.head()

,ᆸ니다,나,농구,더,리그,먹다,밥,배구,보다,비,빕,습니다,않다,액션,야구,어제,었,영국,영화,와,이탈리아,좋아하다,지,축구,친구
1번 문서,0.246645,0.493289,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.287826,0.340917,0.000000,0.340917,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.425995,0.340917,0.287826,0.000000
2번 문서,0.367756,0.000000,0.000000,0.254160,0.000000,0.0,0.0,0.000000,0.254160,0.0,0.0,0.000000,0.000000,0.000000,0.508320,0.0,0.0,0.000000,0.000000,0.309946,0.000000,0.317587,0.000000,0.429159,0.309946
3번 문서,0.292229,0.146115,0.000000,0.403925,0.492583,0.0,0.0,0.000000,0.201962,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.246291,0.000000,0.000000,0.246291,0.252363,0.000000,0.511532,0.000000
4번 문서,0.000000,0.181378,0.305731,0.000000,0.000000,0.0,0.0,0.305731,0.000000,0.0,0.0,0.423323,0.501408,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.313268,0.501408,0.000000,0.000000
5번 문서,0.344453,0.344453,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.580612,0.000000,0.0,0.0,0.000000,0.580612,0.000000,0.000000,0.297463,0.000000,0.000000,0.000000